fix: ../tty/serial/samsung.c: Revert commit from ASB
Partial revert from commit 9f6963fc69e13e5010fec3287bacf7624b66e0e4 where the error was showing up

drivers/tty/serial/samsung.c:1712:12: error: no member named 'dma' in 'struct s3c24xx_uart_port'
                ourport->dma = devm_kzalloc(port->dev,
                ~~~~~~~  ^
drivers/tty/serial/samsung.c:1713:27: error: no member named 'dma' in 'struct s3c24xx_uart_port'
                                            sizeof(*ourport->dma),
                                                    ~~~~~~~  ^
drivers/tty/serial/samsung.c:1715:17: error: no member named 'dma' in 'struct s3c24xx_uart_port'
                if (!ourport->dma) {
                     ~~~~~~~  ^
drivers/tty/serial/samsung.c:1717:9: error: use of undeclared label 'err'
                        goto err;
                             ^

This is because the samsung.h has missing member dma and undeclared err. I should later inspect newer revisions of the kernel. And at least i figured it out when exactly did Exynos850 started, as per https://github.com/torvalds/linux/commits/master/drivers/tty/serial/samsung_tty.c tells me, its around 2021

Also i may have some theory that maybe this particular part is already deprecated but eh, we will see

Signed-off-by: Mizumo-prjkt <bluepearl394@gmail.com>