fix: undefined reference to `do_execveat_common'
ok uhhh i did not expect this one was commented out
for fucks sake, this was commented during first tachyon build and it was
able to compile. So i wasn't aware this was disabled for some reason.

Signed-off-by: Mizumo-prjkt <bluepearl394@gmail.com>