fix: include/linux/sched.h: Fix multiple unnecessary mentions of ANDROID_KABI_RESERVE(7) and ANDROID_KABI_RESERVE(8)
From commit 91ddc6b153bc7a71412667a42bcec30918998b65
This issue exists because of a mistake during processing in the commit
91ddc6b153bc7a71412667a42bcec30918998b65 from
https://android-review.googlesource.com/c/kernel/common/+/1299543

Actions Error https://github.com/MizProject/MizKernel-Kitchen/actions/runs/20539779242/job/59002534716 :
In file included from arch/arm64/kernel/asm-offsets.c:22:
./include/linux/sched.h:1413:2: error: duplicate member 'android_kabi_reserved7'
        ANDROID_KABI_RESERVE(7);
        ^
./include/linux/android_kabi.h:74:38: note: expanded from macro 'ANDROID_KABI_RESERVE'
#define ANDROID_KABI_RESERVE(number)    _ANDROID_KABI_RESERVE(number)
                                        ^
./include/linux/android_kabi.h:63:39: note: expanded from macro '_ANDROID_KABI_RESERVE'
#define _ANDROID_KABI_RESERVE(n)                u64 android_kabi_reserved##n
                                                    ^
<scratch space>:80:1: note: expanded from here
android_kabi_reserved7
^
./include/linux/sched.h:1404:2: note: previous declaration is here
        ANDROID_KABI_RESERVE(7);
        ^
./include/linux/android_kabi.h:74:38: note: expanded from macro 'ANDROID_KABI_RESERVE'
#define ANDROID_KABI_RESERVE(number)    _ANDROID_KABI_RESERVE(number)
                                        ^
./include/linux/android_kabi.h:63:39: note: expanded from macro '_ANDROID_KABI_RESERVE'
#define _ANDROID_KABI_RESERVE(n)                u64 android_kabi_reserved##n
                                                    ^
<scratch space>:72:1: note: expanded from here
android_kabi_reserved7
^
In file included from arch/arm64/kernel/asm-offsets.c:22:
./include/linux/sched.h:1414:2: error: duplicate member 'android_kabi_reserved8'
        ANDROID_KABI_RESERVE(8);
        ^
./include/linux/android_kabi.h:74:38: note: expanded from macro 'ANDROID_KABI_RESERVE'
#define ANDROID_KABI_RESERVE(number)    _ANDROID_KABI_RESERVE(number)
                                        ^
./include/linux/android_kabi.h:63:39: note: expanded from macro '_ANDROID_KABI_RESERVE'
#define _ANDROID_KABI_RESERVE(n)                u64 android_kabi_reserved##n
                                                    ^
<scratch space>:81:1: note: expanded from here
android_kabi_reserved8
^
./include/linux/sched.h:1405:2: note: previous declaration is here
        ANDROID_KABI_RESERVE(8);
        ^
./include/linux/android_kabi.h:74:38: note: expanded from macro 'ANDROID_KABI_RESERVE'
#define ANDROID_KABI_RESERVE(number)    _ANDROID_KABI_RESERVE(number)
                                        ^
./include/linux/android_kabi.h:63:39: note: expanded from macro '_ANDROID_KABI_RESERVE'
#define _ANDROID_KABI_RESERVE(n)                u64 android_kabi_reserved##n
                                                    ^
<scratch space>:73:1: note: expanded from here
android_kabi_reserved8
^
2 errors generated.
make[1]: *** [Kbuild:56: arch/arm64/kernel/asm-offsets.s] Error 1
make: *** [Makefile:1208: prepare0] Error 2

This should (**hopefully**) fix the problem

Signed-off-by: Mizumo-prjkt <bluepearl394@gmail.com>